server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root
  application:
    name: HOTEL-SERVICE #this sets the name to the Hotel-Service module
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8085


#    properties:  # if dialect is not autodetected then set it manually
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true # this is used for this microservice is register with eureka server
#    register-with-eureka: true
#    #below service URL is used to register this service to eureka server
#    # to register this microservice to below server and her we are providing server url
#    service-url:
#      defaultZone: http://localhost:8761/eureka